title: Mikel Pintado
description: > # this means to ignore newlines until "baseurl:"
    Mi blog personal en el que hablo sobre GNU/Linux y mis proyectos.
permalink: ':title/'
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Mikel Pintado # add your name
#author-pic:
about-author: I'm a GNU/Linux fan and gamer who is interested in free and open source software.

# Contact links
email: mikelaitornube2010@gmail.com
website: mikelpint.github.io
github: mikelpint

#Tracker
analytics: UA-106620594-1

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-admin

include: [_pages]
exclude: ["node_modules", "package.json", "yarn.lock"]