title: Mikel Pintado

description: |
  My personal blog where I write about random things.

permalink: ':title/'

author: Mikel Pintado

about-author: >-
  I'm a GNU/Linux user and gamer who is interested in free and open source
  software.

email: mikelaitornube2010@gmail.com

website: mikelpint.github.io

github: mikelpint

discus_identifier: mikelpint

paginate: 6

paginate_path: '/page:num/'

markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-admin

include:
  - _pages

exclude:
  - node_modules
  - package.json
  - yarn.lock